import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{createClient}from'@supabase/supabase-js';import'./styles.css';
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;const supabase=url&&key?createClient(url,key):null;
const areas=['Previdenciário','Trabalhista','Família','Bancário','Consumidor','Trânsito','Saúde','Digital','Imobiliário','Empresarial','Aeronáutico','Pessoa com Deficiência','Criminal','Tributário','Ambiental','Agronegócio'];
const themes=[{id:'classic',name:'Clássico Jurídico'},{id:'executive',name:'Executivo'},{id:'digital',name:'Digital'},{id:'environment',name:'Ambiental'},{id:'realestate',name:'Imobiliário'}];
function App(){const[user,setUser]=useState(null),[dash,setDash]=useState(false),[auth,setAuth]=useState(false),[builder,setBuilder]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[profile,setProfile]=useState({full_name:'',phone:'',oab:'',city:''}),[form,setForm]=useState({title:'Meu Escritório',oab:'',city:'',whatsapp:'',email:'',niches:[],theme_id:'classic'}),[sites,setSites]=useState([]),[articles,setArticles]=useState([]),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false);
useEffect(()=>{if(!supabase)return;supabase.auth.getUser().then(({data})=>setUser(data.user));const{data:{subscription}}=supabase.auth.onAuthStateChange((_,s)=>setUser(s?.user||null));return()=>subscription.unsubscribe()},[]);
useEffect(()=>{if(user)loadData()},[user]);
async function loadData(){if(!supabase||!user)return;const[{data:s},{data:a}]=await Promise.all([supabase.from('sites').select('*').order('created_at',{ascending:false}),supabase.from('articles').select('*').order('created_at',{ascending:false})]);setSites(s||[]);setArticles(a||[])}
function resetForm(){setForm({title:'Meu Escritório',oab:'',city:'',whatsapp:'',email:user?.email||'',niches:[],theme_id:'classic'})}
async function login(e){e.preventDefault();setLoading(true);setMsg('');if(!supabase){setMsg('Configure o Supabase em .env.local.');setLoading(false);return}const{error}=await supabase.auth.signInWithPassword({email:email.trim(),password});setLoading(false);if(error)setMsg(error.message);else{setAuth(false);setDash(true)}}
async function signup(e){e?.preventDefault();setLoading(true);setMsg('');if(!supabase){setMsg('O sistema de autenticação não está configurado.');setLoading(false);return}const cleanEmail=email.trim();if(!cleanEmail){setMsg('Informe seu e-mail.');setLoading(false);return}if(password.length<6){setMsg('A senha precisa ter pelo menos 6 caracteres.');setLoading(false);return}const{data,error}=await supabase.auth.signUp({email:cleanEmail,password});setLoading(false);if(error){setMsg(error.message);return}if(data.session){setAuth(false);setDash(true);setMsg('Conta criada com sucesso!')}else{setMsg('Conta criada com sucesso! Verifique seu e-mail para confirmar o cadastro antes de entrar.')}}
async function saveSite(e){e?.preventDefault();if(!user)return setAuth(true);if(!form.title.trim())return setMsg('Informe o nome do escritório.');if(!form.niches.length)return setMsg('Selecione pelo menos uma área de atuação.');setLoading(true);const site={user_id:user.id,title:form.title.trim(),slug:slugify(form.title),oab:form.oab.trim(),city:form.city.trim(),whatsapp:form.whatsapp.trim(),email:form.email.trim(),niches:form.niches,theme_id:form.theme_id,status:'draft'};const{data,error}=await supabase.from('sites').insert(site).select().single();setLoading(false);if(error){setMsg(error.message);return}setSites(s=>[data,...s]);setBuilder(false);setDash(true);setMsg('Site criado com sucesso. Agora você pode publicar e gerenciar o conteúdo.')}
async function togglePublish(site){const status=site.status==='published'?'draft':'published';const{data,error}=await supabase.from('sites').update({status}).eq('id',site.id).select().single();if(error){setMsg(error.message);return}setSites(s=>s.map(x=>x.id===site.id?data:x))}
function openBuilder(){if(!user){setAuth(true);return}resetForm();setMsg('');setBuilder(true)}
function toggleArea(a){setForm(f=>({...f,niches:f.niches.includes(a)?f.niches.filter(x=>x!==a):[...f.niches,a]}))}
async function logout(){if(supabase)await supabase.auth.signOut();setUser(null);setDash(false)}
if(dash)return <><Header user={user} onHome={()=>setDash(false)} onLogout={logout} onCreate={openBuilder}/><main className="dash"><p className="eyebrow">DASHBOARD</p><h1>Gerencie seus sites jurídicos.</h1>{msg&&<div className="notice">{msg}</div>}<div className="metrics"><div><b>{sites.length}</b>Sites</div><div><b>{articles.length}</b>Artigos</div><div><b>0</b>Contatos</div></div><div className="dash-head"><h2>Meus sites</h2><button onClick={openBuilder}>+ Criar site</button></div>{sites.length?sites.map(s=><article className="site" key={s.id}><div><b>{s.title}</b><small>{s.status==='published'?'Publicado':'Rascunho'}</small><p>{(s.niches||[]).join(' · ')||'Sem áreas definidas'}</p><span>{s.city||'Cidade não informada'} {s.oab&&`· OAB ${s.oab}`}</span></div><button className="ghost" onClick={()=>togglePublish(s)}>{s.status==='published'?'Despublicar':'Publicar'}</button></article>):<div className="empty">Nenhum site criado ainda.<button onClick={openBuilder}>Criar meu primeiro site</button></div>}</main>{builder&&<Builder form={form}setForm={setForm}toggleArea={toggleArea}save={saveSite}loading={loading}close={()=>setBuilder(false)}/>}</>;
return <><Header user={user} onHome={()=>{}} onLogout={()=>setAuth(true)} onCreate={openBuilder}/><main><section className="hero"><div><p className="eyebrow">TECNOLOGIA PARA A ADVOCACIA DIGITAL</p><h1>Seu escritório merece uma presença digital <em>profissional.</em></h1><p>Crie e gerencie sites jurídicos sem precisar programar.</p><button onClick={openBuilder}>⚖ Criar meu site</button>{user&&<button className="ghost" onClick={()=>setDash(true)}>Abrir painel</button>}</div><aside><small>JURISTAS ONLINE</small><h2>Advocacia com excelência e confiança.</h2><p>Site, conteúdo e presença digital em um só lugar.</p></aside></section><section><p className="eyebrow">1. ESPECIALIDADES</p><h2>Escolha suas áreas.</h2><div className="chips">{areas.map(a=><button key={a}>{a}</button>)}</div></section><section className="light"><p className="eyebrow">2. IDENTIDADE VISUAL</p><h2>Temas profissionais.</h2><div className="themes">{themes.map(t=><div key={t.id}><b>{t.name}</b><span>Layout preparado para advocacia</span></div>)}</div></section><section><p className="eyebrow">3. PUBLICAÇÃO</p><h2>Crie, personalize e publique.</h2><p>Seu painel centraliza sites, artigos e contatos.</p><button onClick={openBuilder}>Começar agora</button></section></main>{auth&&<Auth email={email}setEmail={setEmail}password={password}setPassword={setPassword}login={login}signup={signup}loading={loading}msg={msg}close={()=>setAuth(false)}/>}</>}
function Header({user,onHome,onLogout,onCreate}){return <header><button className="brand" onClick={onHome}>⚖ <span>Juristas</span> Online</button><nav>Sites · Nichos · Temas</nav>{user?<div><button className="ghost" onClick={onCreate}>Criar site</button><button onClick={onLogout}>Sair</button></div>:<button onClick={onLogout}>Entrar</button>}</header>}
function Auth({email,setEmail,password,setPassword,login,signup,loading,msg,close}){const[mode,setMode]=useState('login');return <div className="modal"><form onSubmit={mode==='login'?login:signup}><h2>{mode==='login'?'Entrar na plataforma':'Criar sua conta'}</h2><input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/><input type="password" placeholder="Senha (mínimo 6 caracteres)" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='login'?'current-password':'new-password'} minLength="6" required/><button type="submit" disabled={loading}>{loading?(mode==='login'?'Entrando...':'Criando conta...'):(mode==='login'?'Entrar':'Criar conta')}</button>{mode==='login'?<button type="button" className="ghost dark" onClick={()=>{setMode('signup');setMsg('')}} disabled={loading}>Criar conta</button>:<button type="button" className="ghost dark" onClick={()=>{setMode('login');setMsg('')}} disabled={loading}>Já tenho uma conta</button>}{msg&&<p>{msg}</p>}<a onClick={close}>Fechar</a></form></div>}
function Builder({form,setForm,toggleArea,save,loading,close}){return <div className="modal"><form className="builder" onSubmit={save}><div className="modal-head"><div><p className="eyebrow">NOVO SITE</p><h2>Configure seu escritório</h2></div><a onClick={close}>Fechar</a></div><label>Nome do escritório<input value={form.title}onChange={e=>setForm({...form,title:e.target.value})}required/></label><div className="grid2"><label>OAB<input value={form.oab}onChange={e=>setForm({...form,oab:e.target.value})}placeholder="Ex.: BA 12.345"/></label><label>Cidade<input value={form.city}onChange={e=>setForm({...form,city:e.target.value})}placeholder="Cidade/UF"/></label><label>WhatsApp<input value={form.whatsapp}onChange={e=>setForm({...form,whatsapp:e.target.value})}placeholder="(00) 00000-0000"/></label><label>E-mail<input type="email" value={form.email}onChange={e=>setForm({...form,email:e.target.value})}/></label></div><label>Áreas de atuação</label><div className="chips compact">{areas.map(a=><button type="button" className={form.niches.includes(a)?'sel':''}onClick={()=>toggleArea(a)}key={a}>{a}</button>)}</div><label>Tema</label><div className="themes compact">{themes.map(t=><button type="button" className={form.theme_id===t.id?'sel':''}onClick={()=>setForm({...form,theme_id:t.id})}key={t.id}>{t.name}</button>)}</div><button disabled={loading}>{loading?'Salvando...':'Criar site'}</button></form></div>}
function slugify(v){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')+'-'+Date.now().toString().slice(-6)}
createRoot(document.getElementById('root')).render(<App/>);