import React,{useEffect,useState}from'https://esm.sh/react@18.3.1';
import{createRoot}from'https://esm.sh/react-dom@18.3.1/client';
import{createClient}from'https://esm.sh/@supabase/supabase-js@2';

const env=import.meta.env||{};
const url=env.VITE_SUPABASE_URL||window.__SUPABASE_URL__,key=env.VITE_SUPABASE_PUBLISHABLE_KEY||window.__SUPABASE_PUBLISHABLE_KEY__;
const supabase=url&&key?createClient(url,key):null;
const areas=['Previdenciário','Trabalhista','Família','Bancário','Consumidor','Trânsito','Saúde','Digital','Imobiliário','Empresarial','Aeronáutico','Pessoa com Deficiência','Criminal','Tributário','Ambiental','Agronegócio'];
const themes=[{id:'classic',name:'Clássico Jurídico'},{id:'executive',name:'Executivo'},{id:'digital',name:'Digital'},{id:'environment',name:'Ambiental'},{id:'realestate',name:'Imobiliário'}];
const gallery=[
 {src:'https://images.pexels.com/photos/8112153/pexels-photo-8112153.jpeg?cs=srgb&dl=pexels-pavel-danilyuk-8112153.jpg&fm=jpg',alt:'Advogado em reunião com clientes',title:'Atendimento profissional'},
 {src:'https://images.pexels.com/photos/8111815/pexels-photo-8111815.jpeg?cs=srgb&dl=pexels-pavel-danilyuk-8111815.jpg&fm=jpg',alt:'Símbolo da justiça em escritório',title:'Autoridade e confiança'},
 {src:'https://images.pexels.com/photos/7876153/pexels-photo-7876153.jpeg?cs=srgb&dl=pexels-karola-g-7876153.jpg&fm=jpg',alt:'Advogado em reunião com clientes',title:'Relacionamento com clientes'}
];

function App(){
 const[user,setUser]=useState(null),[dash,setDash]=useState(false),[auth,setAuth]=useState(false),[builder,setBuilder]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[profile,setProfile]=useState({full_name:'',phone:'',oab:'',city:''}),[form,setForm]=useState({title:'Meu Escritório',oab:'',city:'',whatsapp:'',email:'',niches:[],theme_id:'classic'}),[sites,setSites]=useState([]),[articles,setArticles]=useState([]),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{if(!supabase)return;supabase.auth.getUser().then(({data})=>setUser(data.user)).catch(()=>{});const{data:{subscription}}=supabase.auth.onAuthStateChange((_,s)=>setUser(s?.user||null));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(user)loadData()},[user]);
 async function loadData(){if(!supabase||!user)return;try{const[{data:s},{data:a}]=await Promise.all([supabase.from('sites').select('*').order('created_at',{ascending:false}),supabase.from('articles').select('*').order('created_at',{ascending:false})]);setSites(s||[]);setArticles(a||[])}catch(e){setMsg('Não foi possível carregar os dados agora.')}}
 function resetForm(){setForm({title:'Meu Escritório',oab:'',city:'',whatsapp:'',email:user?.email||'',niches:[],theme_id:'classic'})}
 async function login(e){e.preventDefault();setLoading(true);setMsg('');if(!supabase){setMsg('Serviço de login temporariamente indisponível.');setLoading(false);return}try{const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message);else{setAuth(false);setDash(true)}}catch(error){setMsg(error?.message||'Não foi possível entrar.')}finally{setLoading(false)}}
 async function signup(){setLoading(true);setMsg('');if(!supabase){setMsg('Serviço de cadastro temporariamente indisponível.');setLoading(false);return}try{const{data,error}=await supabase.auth.signUp({email,password});setMsg(error?error.message:(data.session?'Conta criada com sucesso.':'Conta criada. Verifique seu e-mail para confirmar o acesso.'))}catch(error){setMsg(error?.message||'Não foi possível criar a conta.')}finally{setLoading(false)}}
 async function saveSite(e){e?.preventDefault();if(!user)return setAuth(true);if(!form.title.trim())return setMsg('Informe o nome do escritório.');if(!form.niches.length)return setMsg('Selecione pelo menos uma área de atuação.');setLoading(true);const site={user_id:user.id,title:form.title.trim(),slug:slugify(form.title),oab:form.oab.trim(),city:form.city.trim(),whatsapp:form.whatsapp.trim(),email:form.email.trim(),niches:form.niches,theme_id:form.theme_id,status:'draft'};try{const{data,error}=await supabase.from('sites').insert(site).select().single();if(error){setMsg(error.message);return}setSites(s=>[data,...s]);setBuilder(false);setDash(true);setMsg('Site criado com sucesso. Agora você pode publicar e gerenciar o conteúdo.')}catch(error){setMsg(error?.message||'Não foi possível criar o site.')}finally{setLoading(false)}}
 async function togglePublish(site){try{const status=site.status==='published'?'draft':'published';const{data,error}=await supabase.from('sites').update({status}).eq('id',site.id).select().single();if(error){setMsg(error.message);return}setSites(s=>s.map(x=>x.id===site.id?data:x))}catch(error){setMsg(error?.message||'Não foi possível atualizar o site.')}}
 function openBuilder(){if(!user){setAuth(true);return}resetForm();setMsg('');setBuilder(true)}
 function toggleArea(a){setForm(f=>({...f,niches:f.niches.includes(a)?f.niches.filter(x=>x!==a):[...f.niches,a]}))}
 async function logout(){if(supabase)await supabase.auth.signOut().catch(()=>{});setUser(null);setDash(false)}
 if(dash)return <><Header user={user} onHome={()=>setDash(false)} onLogout={logout} onCreate={openBuilder}/><main className="dash"><p className="eyebrow">DASHBOARD</p><h1>Gerencie seus sites jurídicos.</h1>{msg&&<div className="notice">{msg}</div>}<div className="metrics"><div><b>{sites.length}</b>Sites</div><div><b>{articles.length}</b>Artigos</div><div><b>0</b>Contatos</div></div><div className="dash-head"><h2>Meus sites</h2><button onClick={openBuilder}>+ Criar site</button></div>{sites.length?sites.map(s=><article className="site" key={s.id}><div><b>{s.title}</b><small>{s.status==='published'?'Publicado':'Rascunho'}</small><p>{(s.niches||[]).join(' · ')||'Sem áreas definidas'}</p><span>{s.city||'Cidade não informada'} {s.oab&&`· OAB ${s.oab}`}</span></div><button className="ghost" onClick={()=>togglePublish(s)}>{s.status==='published'?'Despublicar':'Publicar'}</button></article>):<div className="empty">Nenhum site criado ainda.<button onClick={openBuilder}>Criar meu primeiro site</button></div>}</main>{builder&&<Builder form={form}setForm={setForm}toggleArea={toggleArea}save={saveSite}loading={loading}close={()=>setBuilder(false)}/>}</>;
 return <><Header user={user} onHome={()=>{}} onLogout={()=>setAuth(true)} onCreate={openBuilder}/><main>
  <section className="hero"><div className="hero-copy"><p className="eyebrow">TECNOLOGIA PARA A ADVOCACIA DIGITAL</p><h1>Seu escritório merece uma presença digital <em>à altura.</em></h1><p>Crie e gerencie um site jurídico profissional, moderno e pronto para apresentar seu trabalho com credibilidade.</p><div className="hero-actions"><button onClick={openBuilder}>⚖ Criar meu site</button>{user&&<button className="ghost" onClick={()=>setDash(true)}>Abrir painel</button>}</div><div className="hero-proof"><span>✓ Site profissional</span><span>✓ Temas jurídicos</span><span>✓ Sem programação</span></div></div><div className="hero-visual"><img src={gallery[0].src} alt={gallery[0].alt}/><div className="image-badge"><strong>Juristas Online</strong><span>Presença digital para advogados</span></div></div></section>
  <section className="intro"><p className="eyebrow">UMA PLATAFORMA FEITA PARA ADVOGADOS</p><h2>Mais confiança para sua presença online.</h2><p>Escolha sua área de atuação, personalize sua identidade e publique uma apresentação profissional do seu escritório.</p></section>
  <section className="visual-grid"><div className="visual-card large"><img src={gallery[1].src} alt={gallery[1].alt}/><div><span>IDENTIDADE</span><h3>Uma imagem profissional começa pelo seu site.</h3></div></div><div className="visual-card"><img src={gallery[2].src} alt={gallery[2].alt}/><div><span>ATENDIMENTO</span><h3>Apresente seu escritório de forma clara e elegante.</h3></div></div></section>
  <section><p className="eyebrow">1. ESPECIALIDADES</p><h2>Escolha suas áreas.</h2><div className="chips">{areas.map(a=><button key={a}>{a}</button>)}</div></section>
  <section className="light"><p className="eyebrow">2. IDENTIDADE VISUAL</p><h2>Temas profissionais.</h2><div className="themes">{themes.map(t=><div key={t.id}><b>{t.name}</b><span>Layout preparado para advocacia</span></div>)}</div></section>
  <section className="cta"><p className="eyebrow">3. PUBLICAÇÃO</p><h2>Seu escritório pronto para ser encontrado.</h2><p>Crie seu projeto e comece a construir uma presença digital mais profissional.</p><button onClick={openBuilder}>Começar agora</button></section>
 </main>{auth&&<Auth email={email}setEmail={setEmail}password={password}setPassword={setPassword}login={login}signup={signup}loading={loading}msg={msg}close={()=>setAuth(false)}/>}</>;
}

class ErrorBoundary extends React.Component{constructor(props){super(props);this.state={error:null}}static getDerivedStateFromError(error){return{error}}render(){if(this.state.error)return <div style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:24,fontFamily:'Arial,sans-serif',textAlign:'center',background:'#f8f9fb',color:'#0f1729'}}><div><h1 style={{marginBottom:8}}>Juristas Online</h1><p>Ocorreu um erro ao carregar a plataforma.</p><button onClick={()=>window.location.reload()} style={{padding:'12px 18px',border:0,borderRadius:8,cursor:'pointer'}}>Recarregar página</button></div></div>;return this.props.children}}
function Header({user,onHome,onLogout,onCreate}){return <header><button className="brand" onClick={onHome}>⚖ <span>Juristas</span> Online</button><nav>Sites · Nichos · Temas</nav>{user?<div><button className="ghost" onClick={onCreate}>Criar site</button><button onClick={onLogout}>Sair</button></div>:<button onClick={onLogout}>Entrar</button>}</header>}
function Auth({email,setEmail,password,setPassword,login,signup,loading,msg,close}){return <div className="modal"><form onSubmit={login}><p className="eyebrow">JURISTAS ONLINE</p><h2>Entrar na plataforma</h2><input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Senha" value={password} onChange={e=>setPassword(e.target.value)} required/><button disabled={loading}>{loading?'Aguarde...':'Entrar'}</button><button type="button" className="ghost dark" onClick={signup} disabled={loading}>Criar conta</button>{msg&&<p className="auth-message">{msg}</p>}<a onClick={close}>Fechar</a></form></div>}
function Builder({form,setForm,toggleArea,save,loading,close}){return <div className="modal"><form className="builder" onSubmit={save}><div className="modal-head"><div><p className="eyebrow">NOVO SITE</p><h2>Configure seu escritório</h2></div><a onClick={close}>Fechar</a></div><label>Nome do escritório<input value={form.title}onChange={e=>setForm({...form,title:e.target.value})}required/></label><div className="grid2"><label>OAB<input value={form.oab}onChange={e=>setForm({...form,oab:e.target.value})}placeholder="Ex.: BA 12.345"/></label><label>Cidade<input value={form.city}onChange={e=>setForm({...form,city:e.target.value})}placeholder="Cidade/UF"/></label><label>WhatsApp<input value={form.whatsapp}onChange={e=>setForm({...form,whatsapp:e.target.value})}placeholder="(00) 00000-0000"/></label><label>E-mail<input type="email" value={form.email}onChange={e=>setForm({...form,email:e.target.value})}/></label></div><label>Áreas de atuação</label><div className="chips compact">{areas.map(a=><button type="button" className={form.niches.includes(a)?'sel':''}onClick={()=>toggleArea(a)}key={a}>{a}</button>)}</div><label>Tema</label><div className="themes compact">{themes.map(t=><button type="button" className={form.theme_id===t.id?'sel':''}onClick={()=>setForm({...form,theme_id:t.id})}key={t.id}>{t.name}</button>)}</div><button disabled={loading}>{loading?'Salvando...':'Criar site'}</button></form></div>}
function slugify(v){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')+'-'+Date.now().toString().slice(-6)}
createRoot(document.getElementById('root')).render(<ErrorBoundary><App/></ErrorBoundary>);
